name: fare_now_provider
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.5.0+39

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.0
  dio: ^5.3.3
  dropdown_search: ^5.0.6
  equatable: ^2.0.5
  sentry_flutter: ^7.8.0

  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.2
  modal_bottom_sheet: ^2.1.2
  analog_clock: ^0.1.1


  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  get: ^4.6.6
  timeago: ^3.6.0
  json_converter: ^2.0.0
  flutter_easyloading: ^3.0.5
  flutter_vector_icons: ^2.0.0
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  flutter_datetime_picker: ^1.5.1
  permission_handler: ^11.0.1
  group_button: ^5.3.3


  flutter_svg: ^2.0.8

  #  awesome_notifications: ^0.6.21
  file_picker: ^6.0.0
  progressive_image: ^2.0.1
  flutter_document_picker: ^5.2.3
  ensure_visible_when_focused: ^1.1.1

  keyboard_actions: ^4.2.0
  flutter_switch: ^0.3.2
  flutter_keyboard_visibility: ^5.4.1
  country_code_picker: ^3.0.0
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  flutter_credit_card:
  googleapis: ^11.4.0
  #  firebase_messaging:
  firebase_messaging: ^14.7.2
  flutter_local_notifications: ^16.1.0
  flutter_chat_bubble: ^2.0.2
  flutter_polyline_points: ^2.0.0
  flutter_rating_bar: ^4.0.1
  # web_socket_channel:
  laravel_echo: ^1.0.0-beta.1
  socket_io_client:
  image_cropper: ^5.0.0
  sign_in_with_apple: ^5.0.0
  connectivity_plus: ^5.0.0
  flutter_secure_storage: ^9.0.0
  flutter_dialogs: ^3.0.0
  #image_picker_type: ^1.1.2
  image_picker: ^1.0.4
  intl: ^0.18.1
  simple_gesture_detector: ^0.2.0
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.1

  #  flutter_facebook_login:  MIR

  nb_utils: ^6.0.3
  change_app_package_name: ^1.1.0
  social_login_buttons: ^1.0.7
  dropdown_button2: ^2.3.9
  animated_button_bar: ^1.0.0
  fdottedline_nullsafety: ^2.0.1
  group_radio_button: ^1.3.0
  flutter_screenutil: ^5.9.0
  carousel_slider: ^4.2.1
  pull_to_refresh: ^2.0.0
  device_preview: ^1.1.0
  socket_io: ^1.0.1
  logger: ^2.0.2+1
  rxdart: ^0.27.7
  flutter_dotenv: ^5.1.0









dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/cale.png
    - assets/images/
    - assets/providerImages/png/
    - assets/providerImages/png/card_provider/
    - assets/providerImages/svg/
    - assets/subscription icon.png
    - assets/subscription icon.svg
    - .env

  # example:
  fonts:
    - family: Product Sans Regular
      fonts:
        - asset: assets/fonts/Product Sans Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #