// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuK_Hm9HR0G366wB_LKdF-aHzm7eMJRS8',
    appId: '1:604353431757:android:eedde3a03fc356d8e28184',
    messagingSenderId: '604353431757',
    projectId: 'farenow-e023a',
    storageBucket: 'farenow-e023a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4r_XepjZz-K3iUDo6k79dYfkVmKQQ12U',
    appId: '1:604353431757:ios:950b9b6d13ae9fade28184',
    messagingSenderId: '604353431757',
    projectId: 'farenow-e023a',
    storageBucket: 'farenow-e023a.appspot.com',
    androidClientId: '604353431757-d5rsbmmq71299h45f1918so0ch2j2upb.apps.googleusercontent.com',
    iosClientId: '604353431757-gh60424qp908g4sv6mic5e5bqj2l2db5.apps.googleusercontent.com',
    iosBundleId: 'com.app.farenowprovider',
  );
}
